### ISSUE TITLE
Picture Effect Pallet Save Option

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#1231]
Can a color pallet save option be added so I can quickly return to colors I had used with previous image?  We have the function in the main effects color screen.  But, having one inside the picture effect would be a huge help.  Even if the color pallets could be linked to the pallet folder that would be awesome!

Thanks!

**Comment by AzGilrock** [comment]
The Picture Effect has a color pallet?  Took me a couple minutes to figure out you must mean the Effect Assist window?

**Comment by Clyde-L** [comment]
Sorry, was deep into sequencing and building images using the Effects Assist.  Didn't mention it.  Is it something that can be linked to existing pallets?

**Comment by AzGilrock** [comment]
Well I guess anything is possible but its been so long I've looked at that I don't even remember how it works.  That whole needed to be reworked.  It worked well for the 12x50 model I designed it with but if the model is wide and short it doesn't scroll properly and I've had fits trying to figure out wxWidgets to fix that issue.  The dialog is broken in the 3D branch because the positioning has changed.  Bottom line is it needs a lot of work.

**Comment by Clyde-L** [comment]
So you broke it!  Way to go lol!

**Comment by AzGilrock** [comment]
Well it was still useable.  It was drawing the grid like 1/4 size.  You could actually still click and draw but you had to click the cell based on where it should be drawn and not where it's actually drawn...lol.

**Comment by Clyde-L** [comment]
I'm using the 2D version of xLights so this is not an issue at the moment for me :)  I know you have a lot of other stuff to do.  Luckily you can recall/load any image and get the colors back using the tools.  Just easier to transfer colors if you have a pallet.  So put this off till you have free time.

**Comment by AzGilrock** [comment]
We will merge the branches to make it an issue then.

**Comment by cybercop23** [comment]
Available in the nightly and next version.
