### ISSUE TITLE
Enhancement: modifier to change axis when placing models, like polylines, in 3D

### ISSUE THREAD

**Issue by jarogers** [xLightsSequencer/xLights#1443]
Currently when placing models like polylines you can only move in X and Z (xLights Y),  it would be nice to have a modifier key (or similar) to change to Y (xLights Z).

Likewise, when placing a single line (in 3d), it only moves in X.  equally nice to have a modifier to change axis.

Interestingly, when in 2d only, and placing a single line, arches, candy canes, etc., they freely move in X and Z (xLights Y).

**Comment by jarogers** [comment]
and/or make some determination of the 'starting axis' based on view angle, similar to how you fixed 3D pan.

**Comment by AzGilrock** [comment]
I've basically implemented this idea already.  Models will now change the placement axis based on view angle.  Only thing you can't do is switch the axis in the middle of a PolyLine placement but I don't see how to cleanly do that anyways since you really need to be able to rotate the view in the middle of model creation but the same mouse button is used to create points.
