### ISSUE TITLE
Feature request: change axis keystrok in 3D mode

### ISSUE THREAD

**Issue by redhat1283** [xLightsSequencer/xLights#1873]
I would like to have a keystroke (space?) that cycles through the axis of draw when placing props in 3D mode.  This would be incredibly beneficial when doing a house outline using single lines to outline the house.  This could also be accomplished by holding shit while using the rotation handles so that it locks to an axis if you would like.

**Comment by AzGilrock** [comment]
I really don't get what you're saying.  There is no need to "lock" to an axis because it will only move the actual axis you click on.  If you click on the red handle its only the x-axis, green is y, and blue is z.  I don't see anything changing because all the calculations are based on the handle you click on to start a drag or rotation.

**Comment by redhat1283** [comment]
Here's the scenario.  I have a house aligned with the grid.  My street facing gutters are all aligned with the x axis.  When a strand is drawn on them the y values for the end handles should match.  Now say I draw another strand and it draws perpendicular to the gutter.  If I select the strand and hit "x", the strand rotates about the z axis and is now aligned with x.  Now say I want to draw a strand down the side of the house.  I draw a single strand but it draws it aligned with the gutter.  I could now hit "z" and it sounds it to be vertical.  It could also be useful in planar props (window frame, star, flake, flat trees) but you would have to make the xyz key press dictate the axis normal to the plane.  This would also be helpful if datum lines were ever implemented.

**Comment by AzGilrock** [comment]
The way the model creation works it calculates best when the line you are drawing is close to parallel to the screen so it doesn't work well to try to draw along the Z axis if you are looking mainly down the Z axis.  What I could see is detecting the layout rotation and switching between X and Z based on the angle of the view when you start.  And then come up with a way to have it draw vertical instead of horizontal.

**Comment by AzGilrock** [comment]
I've implemented model creation chooses the best axis based on the current view rotation.
