### ISSUE TITLE
Unable to upload to FPP 

### ISSUE THREAD

**Issue by Nickatnite27** [xLightsSequencer/xLights#2344]
I  cannot upload anything to the FPP controllers. Xlights sees all the FPP controllers the light is green in the controller tab. when I use FPP connect, it finds all the controllers properly. When I attempt to upload anything it appears to work and then I get an error message at the end and it doesn't work. I have been on the zoom room tonight with Rick and David, We tried many different ways to get it to work without success. I can upload sequences directly to FPP using FPP file manager and multi sync but not through Xlights. I am using a MacBook Pro macOS 10.15.7 running Xlights 47.2 my FPP versions are 4.2 and 4.3. the show is on its own show network completely independent of any other network. It is a wireless router with a Ethernet switch for extra ports going to each controller. I connect no problem any other way except Xlights. see screenshots below.
Thanks
**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-11-15 at 12 59 12 AM" src="https://user-images.githubusercontent.com/74483214/99178118-0b5a6200-26de-11eb-9f14-73e484b74304.png">

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
<img width="1440" alt="Screen Shot 2020-11-15 at 12 44 24 AM" src="https://user-images.githubusercontent.com/74483214/99177962-86bb1400-26dc-11eb-9331-c72818e89ff0.png">
<img width="1440" alt="Screen Shot 2020-11-15 at 12 43 17 AM" src="https://user-images.githubusercontent.com/74483214/99177963-87ec4100-26dc-11eb-9fff-80868cfd0e0f.png">
<img width="1440" alt="Screen Shot 2020-11-15 at 12 41 25 AM" src="https://user-images.githubusercontent.com/74483214/99177964-89b60480-26dc-11eb-9d51-91e709ead89b.png">
<img width="1440" alt="Screen Shot 2020-11-15 at 12 39 55 AM" src="https://user-images.githubusercontent.com/74483214/99177965-8ae73180-26dc-11eb-9207-d214ee8f058f.png">
<img width="1440" alt="Screen Shot 2020-11-15 at 12 39 42 AM" src="https://user-images.githubusercontent.com/74483214/99177966-8c185e80-26dc-11eb-9bd5-0ca31432086f.png">
<img width="1440" alt="Screen Shot 2020-11-15 at 12 39 29 AM" src="https://user-images.githubusercontent.com/74483214/99177967-8cb0f500-26dc-11eb-94e1-035945cf5145.png">

**Comment by bigwavedave42** [comment]
It looks like no response in awhile, so I'll throw some input out there.

I've seen this happen to people before, and the most common solutions/root cause I've seen:

- Networking connectivity a bit flaky (wireless) and was dropping just enough to make the upload break.  It wasn't noticeable when surfing the internet, just when they were doing these larger uploads.  It seems to be rare this is the problem, but at least switching to wired connection solved it for a few people.
- SD Card was slow and or beginning to die.  Switching to a new GOOD quality SD Card solved the problem.
- People were running out of space.  They may have a 32GB SD Card, but it hadn't been expanded to use all of it, so they only had 8GB available.  
- VERY large sequences just took too long to upload and things started to timeout.  

Since you are able to successfully upload the files directly to FPP, it might not be a FPP issue.  You might want to open this issue up with xLights.  Perhaps their timeout settings are a bit too low or something a long those lines?

**Comment by AzGilrock** [comment]
> Since you are able to successfully upload the files directly to FPP, it might not be a FPP issue. **You might want to open this issue up with xLights.** Perhaps their timeout settings are a bit too low or something a long those lines?

This IS the xLights issue list.

**Comment by bigwavedave42** [comment]
> > Since you are able to successfully upload the files directly to FPP, it might not be a FPP issue. **You might want to open this issue up with xLights.** Perhaps their timeout settings are a bit too low or something a long those lines?
> 
> This IS the xLights issue list.

Indeed it is!  My fault.  I had been working on some FPP earlier and thought I was still over there.  Sigh... not enough sleep.
