### ISSUE TITLE
Preview of Pictures when selected on the timeline

### ISSUE THREAD

**Issue by craskul** [xLightsSequencer/xLights#2387]
**Is your feature request related to a problem? Please describe.**

- I'm frustrated when looking at a sequence and selecting a picture that I can't see a preview of what picture I have selected on the timeline

**Describe the solution you'd like**

- I'd like that when I click on the picture effect in the timeline, that in the effects settings window, I'd see a preview of which graphic it is that I am working on.

**Describe alternatives you've considered**

- Looking at the image name isn't always helpful because it's often buried within the path and one has to scroll in order to see which picture it is.

- Clicking browse to find the image in the directory and previewing it there is a slow and tedious process.

**Comment by Clyde-L** [comment]
Have you tried clicking on the effect, then viewing your model preview or house preview.  I assume you're placing a pic on your mega tree or matrix.  That will clearly show you what image you're looking at, and how it's rendered on the model. 

Also, you can (in windows at least) drag any pic directly from Windows file manager onto your xlights sequence.  That give you the option to see a preview of the image in windows instead of placing on the effect and loading through the "browse" button.

**Comment by AzGilrock** [comment]
Yeah I don't get the frustration.  The picture you select shows up on the model right?
![image](https://user-images.githubusercontent.com/2024669/103243332-c188ac80-4916-11eb-9f8d-0a75522b4a1c.png)
