### ISSUE TITLE
Vendor information in models

### ISSUE THREAD

**Issue by pdobrien** [xLightsSequencer/xLights#2451]
It would be nice if each model had fields for vendor information (vendor name, item ID number/SKU, URL) so that even after I rename something (or after loading up someone else's layout) I can see what it is and where it came from.  Vendors that are already integrated into the model download (Boscoyo, Gilbert, etc.) could provide this info along with the model.

**Comment by derwin12** [comment]
The description is rarely used .. now to get vendors to update their models. I think it will be something that you will likely have to add as your download them. With the new alias feature, I believe it will ask you if you want to retain the original name as an alias. So that may prove helpful as well.

**Comment by derwin12** [comment]
Using the description seems like the best way as vendors are unlikely to update their models. The downloads are entirely under their control.
