### ISSUE TITLE
Copy/Paste Sub Model Node Ranges

### ISSUE THREAD

**Issue by jimswinder** [xLightsSequencer/xLights#2954]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to Copy/Paste the Node Ranges from Sub Model #1 to Sub Model #3 it also copies it to Sub Model #2.

Could also use a "SAVE" button within the Sub Models instead of having to hit "OK" and closing the window down when making a change and having to reopen the window to make other changes.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Sub Models of a Model
2. Click on Sub Model Number 1 and copy Node Range
3. Paste to Sub Model Number 3
4. Node Range Also appears in Sub Model Number 2

**Expected behavior**
Would expect Node Range to only appear in Sub Model I pasted it to
**Screenshots**
Video Attached (Also..tried to attach a .mov file and got the error "We Don't Support That Type Of File"

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.35  64bit

**Additional context**
None

**Attachments**

[Sub Models.zip](https://github.com/smeighan/xLights/files/7578056/Sub.Models.zip)
[Sub Models-Those Blinking Lights RGB.zip](https://github.com/smeighan/xLights/files/7578058/Sub.Models-Those.Blinking.Lights.RGB.zip)

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by derwin12** [comment]
Need some help on this one..
This grabs the submodel that you just clicked on "Two"
`    SubModelInfo* sm = GetSubModelInfo(GetSelectedName());`
But the assignment is STILL looking at the Third line .. where you just pasted in new info
`sm->strands[str] = NodesGrid->GetCellValue(r, 0); // dwe this might still be pointing at the last one???`
So that means that line TWO data is overwritten by the entry of line THREE.
The "workaround" is to be sure and hit enter after making the change on line THREE.. but it is easily reproducible without hitting the enter key.
    
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/e6125e0e-63f6-411c-a9f5-bd3b9481feef)

**Comment by derwin12** [comment]
Seems like a feature of wxWidgets :-) May have to code some trickery here.
https://forums.wxwidgets.org/viewtopic.php?t=39587

**Comment by cybercop23** [comment]
Will be available in the nightly and next version.
