### ISSUE TITLE
Canvas Mode: Artifacting more recognizable as of late

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#3303]
(Edit: Using the 2022.13 version) 

Over the past few months I've noticed a bit more atrifacting with simple Canvas mode effects [see image below].  It usually happens on basic 2 layer effects [see second image], but not in all cases.  

I also experienced this with some Shaders, but it doesn't always happen.  I was unable to reproduce an instance and add that to the attached package sequence.

Thanks for checking,
Clyde

![image](https://user-images.githubusercontent.com/12719816/176295605-faec1aa7-b986-43ae-87f3-de82e17a6912.png)
![image](https://user-images.githubusercontent.com/12719816/176299080-ab1c3324-21bc-4f1d-bf35-92b53a90d1f6.png)
[Artifacting.zip](https://github.com/smeighan/xLights/files/9005569/Artifacting.zip)

**Comment by merryoncherry** [comment]
Is it just the preview or does it occur in final render?

**Comment by craiz** [comment]
I found this bug while looking for 3288.  I opened 3288 and found that some instances are fixed in 2022.13 there are still some cases where I can still reproduce the artifacts.  For me it is different combinations of buffer size or position mismatch between the effect with canvas (off in my case) and the effect being included in the canvas.  I will package a sequence which shows the issue still repro'ing.  I'm not sure if it is the same as what Clyde is seeing.

**Comment by Clyde-L** [comment]
> Is it just the preview or does it occur in final render? Also curious if you tried since #3288 was fixed?

I'm running off of the latest version 2022.13.  this is after laying the effect down, then clicking render.

**Comment by cybercop23** [comment]
@Clyde-L is this still happening on the latest version?

**Comment by Clyde-L** [comment]
Issue was fixed but never closed.
