### ISSUE TITLE
Moving Head "rest/home"postion

### ISSUE THREAD

**Issue by danielrenwick** [xLightsSequencer/xLights#3315]
With MHs becoming increasing popular and more vendors adding them to their sequences, is there any way possible to make automatic adjustments if the vendors home/rest position (pan orientation in layout) is different to your own? For example, if one person has their rest position to the right and they map a sequence from a vendor who has their rest position to the front, then all the effects are in the wrong direction and you have to change every pan effect. The tilt isn't as bad as most vendors have a similar tilt orientation.

**Comment by kbostick88** [comment]
As a sequence vendor with Moving Heads, we get this request often. I think Pan and Tilt should both have some type of "home" adjustment per sequence, so the person with moving heads can easily map them over from any vendor regardless how the vendor has their MH set up.

**Comment by tmeyermn** [comment]
This is becoming a frequent request for me as well. Moving heads are already a frustration point for customers which is why they want someone else to do the sequencing for them. However, not all vendors choose the same home position (pan orientation).

**Comment by AzGilrock** [comment]
If I do more moving head work like I planned I was not going to try to hack anything into the existing functionality it would be too much of a mess and be very limiting on getting the features I wanted.  I was going to create a new model type and a new Moving Head effect that would need to be used with the model kinda like using the Servo effect for servo models.

**Comment by ABurton26** [comment]
Moving heads are getting purchased by more light enthusiasts. Vendors are creating amazing sequences however when you are dealing with multiple vendors their set up for pan/tilt etc may not be the same and causes problems for the sequence. We need the opportunity for an easy mapping feature with moving heads. I had to reach out to two different sellers to get a better understanding as to what I needed to update in my sequence to make it work.  It takes hours to go through each DMX line of the sequence to try to figure out the changes that need to be made. If I don't make these changes, I would not be able to use the sequence because the moving head would shine straight down or in the faces of my audience.  Thanks

**Comment by AzGilrock** [comment]
Things that help out vendors plays very little into our motivation of donating our time.

**Comment by computergeek1507** [comment]
I find it very ironic that vendors really want a feature that will help them make money.

**Comment by tmeyermn** [comment]
Ironically the vendors are power users and do have valuable input. That being said the person that created the enhancement request wasn't a vendor. I don't believe that ABurton26 is a vendor either. I get your sentiment Scott, but this wouldn't help vendors make money, we are just recognizing a pain point for users. Being in the software biz myself I know marking something as an enhancement is pretty much the kiss of death anyway lol 

There were absolutely no expectations, just awareness since this seemed to be overlooked since June. 

Keep up the good work guys, you've been cranking out some amazing things!
Tim (Pixel Sequence Pros)

**Comment by RodneyBurton26** [comment]
Audra and I have moving heads in our show to help give people something new and innovative to see along with the lights. She has been trying to crack the code on them every since we purchased them last year in a group buy. So there's definitely more people out there that are having the same struggles as us. This has been a very challenging task to say the least. We have a multitude of sequences from different vendors that utilize moving heads. We have talked to all of them in order to get help to make the necessary adjustments to our movers to match their sequences.  We aren't just asking for the help for ourselves we are trying to be proactive in what others will face when they purchase some type of moving heads. We really need the gifted tools that developers continue to add to XLights so that users like us have to opportunity to bring our visions to life. Speaking from experience our current show wouldn't have been able to grow without all of the incredible changes that have been made over the past 4 years. It was awesome to actually see and hear some of the background about the developers and the FMM this past year. I have nothing but respect for each one of you because of your generosity to XLights. Any help that you can give us will be greatly appreciated. Thanks so much.

**Comment by kbostick88** [comment]
Hey Scott,I am not sure how this feature would make vendors more money, right now most the vendors charge for mapping/importing services. This feature would actually reduce those request and this take money out of the pocket of vendors while allowing more users a less frustrating experience for using a sequence with moving heads.On Sep 21, 2022, at 5:24 PM, Scott Hanson ***@***.***> wrote:﻿
I find it very ironic that vendors really want a feature that will help them make money.

**Comment by AzGilrock** [comment]
I don't think we need convincing that people want changes.  I've had ideas for changes way before all the users started talking.  I started some changes over a year ago but quit working on it when other developers kept messing with my DMX code.  When I first created all the DMX capabilities I'm pretty sure it pre-dated the ability to even import a sequence so there were no sequence vendors and therefore it was never considered as a design goal.  I've worked with Tom BetGeorge on ideas for a big overhaul but other work keeps going on that is in a different direction than I'd like to see things go.  That's the issue with these freeware projects.  So I've started losing interest in completing those ideas.  Coordination between developers has never been very  good on this project.  Software guys tend to like to work alone and we like our own ideas better than the other guys...lol.

The ideas from Tom's helper that created a design document for us would be a whole new level for moving heads but existing sequences would need to be completely re-done.  The old ways would still work but if you want the new features things would need to be re-done.  The position needs to be abstracted.  The command should be an absolute position and then the model parameters would define the home positions and then we figure out how to get to the absolute command.  It should support 16 bit moving heads so I was going to have the new model type use the Servo capability which some moving head sequencers already use.  It also needs to support the 2 bytes of that 16 bit command being in either little endian or big endian and not necessarily contiguous.  I had plans for a new Moving Head effect that would have several tabs for different ways to move the head.  It could be direct position commands, a tab for a path command, a tab for specific target positions such as all the heads spread out in a fan shape.  There would be a library of stored positions with the ability to save new position sets.  Scott created a DMX Path effect which I had planned to be just one small feature of the new effect I was going to do.  The effect would be able to control multiple heads so that the whole array could follow the path and you could command offsets for each head.  With the way xLights works effects have to be placed on models so it makes it a pain when what we really would want for moving heads is the ability to select the models its moving inside the effect and not because of what model it was dropped on.  So the effect would need to be able to get a list of all the models in the model group its dropped on to be able to send a different command to each model in the group.

**Comment by AzGilrock** [comment]
I'm not saying we never do anything to help sequence vendors.  Most of the big players that have been around awhile talk to me directly so you never see us working together.  They've treated me well giving me free memberships or sequences over the years.  Some of them donate significant amounts to xLights.  I never really see what's coming in until Sean sends it out every year or two.  That's always a good motivator.

**Comment by danielrenwick** [comment]
Thanks guys for the latest change. I found the remapping new pan values made a big difference and very easy to do. I was able to make a sequence look great in 2 minutes as opposed to several hours of having to change every pan effect. I haven't figured out yet what can be done when some people have a positive value as opposed to a negative value in the pan/tilt deg of rotation, but it is still a big step forward and welcomed addition.

**Comment by AzGilrock** [comment]
A negative value just reverses the direction.  I haven't checked out the remapping but can't you use a value that flips the sign if needed?

**Comment by danielrenwick** [comment]
I've messed with so many values and even tried to remap the tilts without success. Most of it is ok, just some effects will be facing backwards instead of forwards, so I guess people can just manually change those. Thanks for all the devs on the mHs advancements recently, it is greatly appreciated.

**Comment by AzGilrock** [comment]
Well I’d bet it can either be done or improved but you would need to provide a simple example.  It’s best if you can create a new layout with just one MH and just a few effects with the problem.  And I guess a sequence to import which again is best if it’s simple.  I know it’s not fun to create that content but welcome to our world.

**Comment by computergeek1507** [comment]
The Liner equation, y=mx+b can map values 20 to 230, 10 to 240. If you have other examples we can look into it.

**Comment by tmeyermn** [comment]
I used the linear equation yesterday for different pan orientation and reversed direction and it works great!

**Comment by cybercop23** [comment]
Seems like #4260 will address this correct Gil? So so, can this be closed?
