### ISSUE TITLE
ESPixelStick V4.03 Beta Crashes xLights64

### ISSUE THREAD

**Issue by lathemaster** [xLightsSequencer/xLights#3326]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
Wanting to test ESPixelStick running sequence from SD Card
While testing a simple 2 color 3 Minute Butterfly effect on a 48 pixel WS8211 set of pixels the sequence
froze at about 1 minute of play. Then when the playback is beign reset xLights crashed

OS: Window 10
xLights 2022.13-64
ESPixelStick Hardware V3
Firmware: V4.03 Beta

[xLights_dbgrpt-11476-20220707T151246.zip](https://github.com/smeighan/xLights/files/9066793/xLights_dbgrpt-11476-20220707T151246.zip)

**Comment by keithsw1111** [comment]
Your description seems to be missing details and contains extraneous details so i am struggling with how to reproduce your problem.

You talk about the use of an SD Card but that seems irrelevant as best I can tell.

You then talk about playback ... I assume with output to lights on but you dont say. You say it froze but somehow you managed to begin playback again ... is that because you killed and restarted xLights.

Also for some reason your crash log is missing the one critical file that i need to look into the crash so i am flying blind here with only your description of your actions to go by and as you can see i am struggling to accurately follow those steps.

One thing I note is you have auto upload configuration ... try turning that off. On my machine that seemed to cause all sorts of issues.
