### ISSUE TITLE
Enhance tools / Batch Render window to match tools/ FPP connect

### ISSUE THREAD

**Issue by lewislawrence2** [xLightsSequencer/xLights#3605]
**Is your feature request related to a problem? Please describe.**
Please make the Tools / Batch Render window match the Tools / FPP connect window.  It would be nice to be able to sort alphabetically or by last modified date.

**Describe the solution you'd like**
I would like both windows to have the same sort functionality

**Describe alternatives you've considered**

**Additional context**

**Comment by OnlineDynamic** [comment]
Think showing the latest rendered date and being able to sort by that is really important

Would be good to also have batch render dialog improved to have:

- Ability to select all / deselect all
- Ability to show if channels/layouts have changed since last render so we know that sequence needs to be re-rendered
- Ability to run a batch 'check sequence' against the list and highlight any sequences that have 'errors' so the user knows what needs to be corrected before including in the list of sequences to batch render

**Comment by cathelest** [comment]
You can select/deselect all by right clicking the list,

**Comment by cybercop23** [comment]
You can now (been there) sort on name and date and also right click to select/deselect.
@lewislawrence2 please review and close this issue.
