### ISSUE TITLE
Can no longer rearrange timing tracks in views

### ISSUE THREAD

**Issue by DoctorWiz** [xLightsSequencer/xLights#3645]
**Describe the bug**
Timing tracks can no longer be rearranged or reordered in the views.  I know you've never been able to change their order in the Master View (but I sure wish you could, hint hint) but you were able to change their order in other views.  This no longer works.  Clicking the up or down arrows in the display elements dialog has no effect.  Drag-drop does not work either.

**To Reproduce**
Create a sequence.
Create/add some timing tracks
Open display elements
Create a new view
Add the timing tracks to the new view
Attempt to change their order using the ^ up and v down buttons, and/or by drag-dropping.
--> Their order will not change!

**Expected behavior**
You should be able to rearrange timing tracks in custom views (other than Master View (and preferably there, too, hint hint))

**Versions (please complete the following information):**
 - OS: Windows 10 Pro 22H2 build 19045.2364
 - xLights version 2022.22

**Workaround**
Rearrange timing tracks by manually editing the sequence file.  But that effects ALL views.

**Attached:**
[Timing Track No-Reorder Demonstration.zip](https://github.com/smeighan/xLights/files/10255777/Timing.Track.No-Reorder.Demonstration.zip)

**Comment by DoctorWiz** [comment]
Nudge nudge.  Still not working in 2023.08, and rather annoying.

**Comment by bcarriveau** [comment]
> Nudge nudge. Still not working in 2023.08, and rather annoying.

Could offer a fix or ask nicely . Watch them jump now with a rather annoying contribution😂🙈

**Comment by DoctorWiz** [comment]
I would gladly fix it and push it back to the repository if my C++ skills were better, along with other open bugs.  Alas, my C++ skills are "meh" at best.
I mentioned this bug in person to Keith at the Florida Mega-Mini and he thought it was "something simple" and he said he even had a good idea where the problem was.  He just didn't elaborate.
Simply a friendly reminder trying to get this back onto the dev's radar.  I can't be the only one who finds this bug annoying.  (Fortunately, not critical)
I have the utmost respect and gratitude to all the developers.  I make a $$ donation every year.

**Comment by derwin12** [comment]
This was disabled 2 years ago .. 
![image](https://github.com/smeighan/xLights/assets/4643499/3d37c538-926c-44e2-8dd2-a07ba7f81183)

**Comment by AzGilrock** [comment]
I wouldn't call what I did "disabling it".  Pretty sure it wasn't really working as people expected anyways.  I didn't do the initial dialog but I did a major overhaul of it many years ago.  Then Keith overhauled it to make it work with drag/drop.  There were several bugs with the drag/drop that I went in and fixed later.  There was comment in there about not sure why we need to restrict something to the master view and I discovered why and updated the comment with that code.  The problem is that Views are global to the whole show folder.  The Master View is really what you would call a Sequence View.  Timing tracks are owned by the sequence so it doesn't make sense to define timing track names in a global view when they are exclusive to each sequence.  Its possible you could create the same name in all sequences of a folder but that's not guaranteed.  I did make sure you could reorder the timing tracks in the Master View so if that is broken it could be fixed.  I'd want to hear someone confirm that.

**Comment by cybercop23** [comment]
Just checked 2024.2 and you can reorder TT in MV. Per discussion above and since that works, can this be closed?
