### ISSUE TITLE
Aspect ratio for Matrices 

### ISSUE THREAD

**Issue by jasejman2000** [xLightsSequencer/xLights#3863]
I can't seem to find this option so I thought I'd tag it as a feature request. 

Would love to see Aspect ratio conversion for the Matrices. I have 2 window matrix's that are made from 2811 strip cable tied to a 1.5inch grid Matrix panel from Extreme Lighting Displays (I think it's called Chromas Mesh on Troy's site).  Because I have used strip (30LPM)  the number of pixels in the X direction are slightly closer spaced than in the Y direction. So X spacing is ~33mm Y spacing is ~38mm. Due to this the aspect ratio of my Matrix is slightly off when apply any effects to them. Pretty much unnoticeable until I put a circle on it which looks more like an Oval rather than a circle.

It would be great to have some kind of setting within the Matrix model so I can set an XY aspect so I can correct for this kind of anomaly. Most matrices are 1:1 but in my case it's ~1:1.15. Would be nice to have an option to correct for ones that aren't identical in the XY directions.

The way I've been dealing with it in the past is to pre change the aspect of my video files by 1.15 etc. when I use them on the Matrix's when I know I want pure circles. 

Apologies if I missed a setting somewhere that corrects for this. 

Here's an example of the slight differences I see. 

Circle on my matrix 
<img width="242" alt="Screen Shot 2023-07-03 at 8 09 38 am" src="https://github.com/smeighan/xLights/assets/50489084/af28084f-57cf-4a4e-a136-903faeac8a7e">

Vs circle in Model Preview
<img width="219" alt="Screen Shot 2023-07-03 at 8 09 51 am" src="https://github.com/smeighan/xLights/assets/50489084/9017be70-99f9-424a-8ffd-8f12dd1e84b9">

Here's a pic of my strip on the 1.5inch grid where you can see the spacing isn't quite 1 to 1 in XY directions.
![65846061814__D20D3E2B-F221-41DD-91EC-D00C2ED1D4DE](https://github.com/smeighan/xLights/assets/50489084/14658348-37c0-48e5-8c10-8923cafdfc74)

**Comment by merryoncherry** [comment]
This is a difficult thing to do.  There are many effects in xLights, like shockwave, circles, ripple, pinwheel, etc., that assume that the aspect ratio is square when they draw circles, stars, squares, lines at fixed angles, etc.  

Here are some things you can do with the existing features, and notes on the limitations of same:
1. Put "per preview" render style on the effects
2. Put the model in a group, and set the default render on the group to minimal grid or per preview, and apply effects to the group
3. Convert the matrix to a custom model and put some gaps in to even it out.  Make a submodel with the strands in it also.

Note that all of these approaches cause xLights to make a buffer with square aspect ratio and more resolution than your matrix, and then map the result onto your matrix once rendered.  So, the limitation of all of these approaches becomes that, since some effects do not look good with gaps in between pixels, you have to decide on each effect separately what to do... that is for #1 decide to use a different render style, for #2 decide if you want to apply to a group or not, for #3 decide to use the model or submodel.

**Comment by jasejman2000** [comment]
Cool thanks for the tips and quick response. That all makes sense. Sounds like a significant rewrite for a seemingly simple feature that's for sure.

**Comment by derwin12** [comment]
Isnt this addressed using the ruler and 3d xlights? Then you can put in actual measurements. Optionally return to 2d.

**Comment by merryoncherry** [comment]
The point is some render styles (say, "per preview") take real world location into account and those take care of aspect ratio for you if you've set the physical dimensions properly, but other render styles (say, "default") just lay the strands out on a grid that is packed tightly together and render effects to it, so if you do that with a matrix that is not 1.0 aspect ratio then squares will not be square in real life.

These two methods have different pros and cons depending on the effect, as some effects are quite sensitive to the render buffer resolution, or if certain rendered pixels map to a cell with no nodes in it, that can look bad too.

If you spend a few minutes playing in xLights with, for example, the text effect on a matrix that is really stretched out, you will see what I mean.  The results vary a lot by effect type.

One thing that can be done for import sequences is save the effects on the source sequence as a video, then use the video effect in the imported sequence, as video is one of the better ones for handling aspect ratio correction with interpolation.

**Comment by cybercop23** [comment]
@jasejman2000 can this be closed? If so, can you please close it?
