### ISSUE TITLE
MOVING HEADS: Fine Control for Pan, Tilt, Dimmer etc. 

### ISSUE THREAD

**Issue by jasejman2000** [xLightsSequencer/xLights#3871]
I searched through all the moving head requests and couldn't see this. So please correct me if I've missed it.

It would be great if there was a fine control for Pan, Tilt, Dimmer and any other custom controls for DMX moving heads. This essentially allows them to be 16 bit instead of 8 bit for some functions. Lots of newer moving heads have this as it allows smoother slow movement. With 8 bit control 1 step of a 540 degree panning head would represent 1.5 degrees which can be pretty obvious when pointing a long beam into the sky. With 16 bit control it would represent 0.008 degrees hence allowing for much finer slow movements and much less noticeable steps. I've attached a DMX traits PDF from a moving head to demonstrate how it's usually mapped. You can see in fine control mode (16 bit mode) the moving head has extra DMX channels allocated for fine control.

<img width="1898" alt="image" src="https://github.com/smeighan/xLights/assets/50489084/f49c8e8b-ac78-441b-87b7-56280a0da662">

When in this mode, essentially the coarse control is the upper 8 bits of the axis (say pan for example) and the fine control is the lower 8 bits of the axis. Giving a full 16 bits of control.

Not sure if this is easy to implement because WS2811 is 8 bit so I'm guessing the underlying architecture is built around that. 

With some of my moving heads I can control the speed of the pan/tilt axis via one of the DMX channels but doing using fine control instead would allow much more precise control of the head's position when doing slower movements.

Would be great to see this added sometime in the future.

**Comment by AzGilrock** [comment]
I’ve already got 16 bit capability in the new Moving Head Model I’m working on.  And the coarse and fine channels do not need to be beside each other because I’ve heard some manufacturers put the fine channels at the end as an afterthought when they went from 8 to 16.  Currently you can control a 16 bit moving head with the servo effect in lights but the channels have to be beside each other.


￼

**Comment by AzGilrock** [comment]
I’ve already got 16 bit capability in the new Moving Head Model I’m working on.  And the coarse and fine channels do not need to be beside each other because I’ve heard some manufacturers put the fine channels at the end as an afterthought when they went from 8 to 16.  Currently you can control a 16 bit moving head with the servo effect in lights but the channels have to be beside each other.

<img width="506" alt="Screenshot 2023-07-07 at 3 47 56 PM" src="https://github.com/smeighan/xLights/assets/2024669/600176f9-280b-43eb-90c4-f3efe4ed9454">

**Comment by jasejman2000** [comment]
Oh that's cool! Can't wait for it to be released. Didn't think of trying the servo model. Will have a play with that in the meantime!

**Comment by computergeek1507** [comment]
> I’ve already got 16 bit capability in the new Moving Head Model I’m working on.  And the coarse and fine channels do not need to be beside each other because I’ve heard some manufacturers put the fine channels at the end as an afterthought when they went from 8 to 16.  Currently you can control a 16 bit moving head with the servo effect in lights but the channels have to be beside each other.
> 
> <img width="506" alt="Screenshot 2023-07-07 at 3 47 56 PM" src="https://github.com/smeighan/xLights/assets/2024669/600176f9-280b-43eb-90c4-f3efe4ed9454">
> 
> 

Would it be possible to make the current model auto update to the new model? It will be confusing to have three different moving head models that do different things and only one works with your new effect.

**Comment by AzGilrock** [comment]
I'll look into it but probably when its closer to done.

**Comment by AzGilrock** [comment]
The thing is people have been sequencing those models like 10 different ways so I'm not sure I'll know how to test all the variations to know if anything breaks.  People use On effects down on the channels and submodel groups and all kinds of ideas I probably don't even know about.   The initial safe thing was to not mess with any of the existing stuff.

**Comment by computergeek1507** [comment]
I assume the new model would still support node level on effects and the DMX effect and they would still work or is this not true?

**Comment by AzGilrock** [comment]
I know the DMX still works on the new model but haven't tested anything at the node level.  I assume it probably still works.  I'm not going to rush it out so I'll see what can be done to migrate.

**Comment by computergeek1507** [comment]
I am really interested in the movement part, there is an open source software called QLC+ that does movement with "EFX Effects". they have Circle, Square, Line, Figure 8 precanned movements. It uses Sin, Cos, and logarithmic equations on the pan and tilt values.

**Comment by AzGilrock** [comment]
Got value curves working.  Wanted to show how I'm doing it in case any devs have heartburn with it.  Since I don't have controls for all 8 heads I'm having to store the commands for each head down in a textbox that I grab them from later when rendering.  So its not going to look nice when a value curve's settings are thrown down there but it does work nice.  Can't really think of a better way except I did have the idea to have another set of hidden textboxes that hold the ugly settings string and then I can display "prettier" text in the displayed textbox.  I'll give that a shot and see if it works.

In this screenshot there is a value curve for pan and tilt on 1,2,3,4 and then a static pan position and a tilt value curve on 5,6,7,8
<img width="358" alt="Screenshot 2023-07-08 at 9 46 12 AM" src="https://github.com/smeighan/xLights/assets/2024669/6c2eb129-d20c-4d61-8d37-b1c5c6304ed6">

**Comment by AzGilrock** [comment]
Turns out the hidden textboxes works pretty good

**Comment by jasejman2000** [comment]
@AzGilrock You might already know this but the GrandMA software is free to download if you want some examples of lighting layouts and common functions.

**Comment by HPMDS** [comment]
I don't know if this would be the better place to say this feature.
But this feature of selecting which fixture from a group you want to apply the effect with a value curve would be really awesome to be able to apply timeout on value curves based on the position of the fixture (From Middle, To Left, To Right...) relative to others, so values curves could run into multiple fixtures with proportional or a fixed timeout on the curve for each.

**Comment by AzGilrock** [comment]
What the heck is a timeout on value curves?   Don’t bother answering you’re gonna get what I give you.

**Comment by AzGilrock** [comment]
The only time offset feature is going to be if you use pathing you can specify a time offset to stagger each head based on its position

**Comment by jasejman2000** [comment]
@AzGilrock Can't wait to see what you implement. Really appreciate your work on this. It's going to be a game changer for those of us using moving heads in our displays. 

> The only time offset feature is going to be if you use pathing you can specify a time offset to stagger each head based on its position

**Comment by computergeek1507** [comment]
Will it work with any amount of moving heads or only 8?

**Comment by AzGilrock** [comment]
Gotta draw the line somewhere….8 will cover 95% of users.   You can run more than 8 by using 2 groups or by doubling up positions.   For instance you could run 16 heads but they would need to map into 8 positions

**Comment by computergeek1507** [comment]
I assume it could be generic and make render styles for odds, even, thirds etc. Then it could support 2,4,6,8,9,10,12 etc.

**Comment by AzGilrock** [comment]
The heads need to be assigned a position in the group in model properties.   So multiple heads can be assigned to the same position.  I’m supporting 8 positions.   Even if someone has more than 8 heads it’s unlikely they have all of them in a straight line that need to be controlled in a single group.

**Comment by computergeek1507** [comment]
The order of the heads in the group could be the head position and new render styles could be used to set what is used

**Comment by derwin12** [comment]
I think this has been pretty much covered..
