### ISSUE TITLE
3d depth issue with imported props

### ISSUE THREAD

**Issue by SniperMunyShotz** [xLightsSequencer/xLights#3876]
I am noticing that when you import a prop on 3d, the prop is importing depth in the 1000's of inches like 8572, 7555 etc and that messes with alignment of props from the front etc until the depth is changed to 2 inches.  Is there a way to have xlights default the depth to 2 inches?

**Comment by AzGilrock** [comment]
What prop are you importing cause I don't see that.  And does xLights say its inches?  That must be new because those values were unitless when I wrote it.

**Comment by merryoncherry** [comment]
Let me try to explain it a bit better, as I've seen it also (primarily on custom models).
In a 3D layout, pick download or import.
Drag a box on the layout.
Pick the model to import.
Once complete, "Scale Z" might be set to something like 8.381; but I've also seen it set to much larger numbers.
![image](https://github.com/smeighan/xLights/assets/102841136/f7502869-203f-46e4-8665-5e9fa4fcf919)

Anyway, sure Gil, "Scale Z" is unitless, but if you have a ruler in your layout, there is a conversion done... I think that's what the reporter is referring to.
![image](https://github.com/smeighan/xLights/assets/102841136/5b3f45c3-801a-45ab-8656-fee144fcbdef)

I would also point out that it does cause inconvenience, if you don't set them consistently it messes with the depth of things and what is in front of what, so I do routinely go reset it in my layout.

**Comment by derwin12** [comment]
Could it be an uninitialized value after the import?

**Comment by AzGilrock** [comment]
Import positions are defined by where you draw the box for import

**Comment by derwin12** [comment]
> Import positions are defined by where you draw the box for import

Even the Z?

**Comment by AzGilrock** [comment]
I’ll try to double check it but yeah I thought the box you draw defines where the import lands

**Comment by SniperMunyShotz** [comment]
This pretty much does it for any prop that is 2d imported into 3d with the ruler enabled.  Boscoyo cow model was the latest that imported at 7500 inches.

**Comment by AzGilrock** [comment]
Yeah the problem to me is that the depth is mis-calculated for Custom models.  I can cause the same situation without importing a model because the ScaleZ parameter is what controls the depth on that model.  You can see that value change when you change the Depth number.

The import process calculates those parameter values in order to keep the box you drew the same size.  So you'll see the ScaleZ has to increase to a high value to get the box to stay the same size.  If you create a new Custom model from scratch you'll see it starts out with the same visual depth in white boundary box.  Then open the data dialog and change the grid size to 350 x 350 and you'll see the depth get really tiny and to get that box to go back to the size it started out yet you would need to increase the ScaleZ to a big number.  That's what's happening during the import.

I think the problem is that the depth for custom models is being calculated based on the width times the ScaleZ and the width is calculated based on the grid size.   So when the grid width is large but the grid depth is 1 it takes a big ScaleZ to widen that box.  The thing is we can't just willy nilly start changing these values without messing up everyone's models.  The Custom model is drawn with the BoxedModelScreenLocation class which is also used for other model types like a Tree model so if we change how those values are calculated it will change how all those items are drawn.  So bottom line is it will need some thought for how to fix this.  Its obviously lying about the depth because if I set a Custom model to 4'x4'x4' the depth looks like 1".

**Comment by cybercop23** [comment]
Can this have the same "update code" that after 2024.3 the Z will be 1 on custom models import if it has some large >x|y value. I get this all the time and I just go in and set the depth to 1. Very very very few models aren't 1 so fixing it to 1 when it is an _invalid_ value seems to make sense.
