### ISSUE TITLE
Ripple New 

### ISSUE THREAD

**Issue by Darzoom** [xLightsSequencer/xLights#3880]
**Describe the bug**
When using New Ripple with the value curves, Timing Track Toggle, Timing Track Fixed Fade or Timing Track Proportional, a single pixel it lite up on the model in model preview.  This does not happen when setting Cycle CNT to a number value.   

**To Reproduce**

1. Add a Ripple (new) on a matrix 
2. Select one of the above value curves for Cycle Cnt
3. The pixel will appear.
4. Set the CYcle CNT to a number value, pixel will not be seen

**Expected behavior**
No pixel when using value curves. 

**Versions (please complete the following information):**
 - OS: Mac Intel Processor Monterey 12.6.7
 - xLights version 2023.10 wxWidgets 3.3.0

**Comment by merryoncherry** [comment]
I may not be seeing what you are seeing, or understand what you are trying to do.

When I do what you say (In a new sequence, put Ripple set to "Lines Both") on a small matrix, cycle count set to timing track value curve, I see a pixel with very small red circle around it.

This is not what I see with cycle count 1, which shows an explode, but is exactly what I see when I set cycle count to 0.

If I set it to "Implode", I see a big circle that doesn't move, in both cases.

I get similar results with "Old" render style - there is no movement and the shape stays very small or very large depending on implode/explode.

So this is consistent with the idea that the timing track value curve is returning 0 when there's nothing interesting in the timing track.

Now, personally I have trouble with some of the things like "Cycle count" having the value curve; it would have been better to have a "cycle phase" instead.  This is why I added a "None" movement with "Scale" to it, which allows you to just change the size over time.

But what is your goal... what effect are you trying to achieve with the timing track?

**Comment by Darzoom** [comment]
I am expecting the value curves to work without the small dot as the number value in the Cycle Count does.  The numbered Cycle Count starts without the dot.  I’d expect the same thing with value curves.

**Comment by derwin12** [comment]
I think there is a zero being produced on the value curve or something.. A picture ..
![image](https://github.com/smeighan/xLights/assets/4643499/0cfea7f7-36bb-4ea6-b848-9cd7ddc37f6e)

**Comment by AzGilrock** [comment]
What are you guys calling the “small dot”?  The period in a floating point value?

**Comment by merryoncherry** [comment]
:-D  The single white pixel from the 0-size shape, plus the red (by default) rings around it if it ripples outwards from there.

**Comment by Darzoom** [comment]
There is a single pixel that lights up.  Hence, “small dot”.

**Comment by AzGilrock** [comment]
Ah ok.  Yeah I kind of agree about the value curves on a Cycles parameter. I was just adding a Cycles field to my new Moving head effect I'm working on and was thinking it didn't make sense to change the cycles in the middle of the effect.  With a moving head your probably not gonna want it to make the jump that would happen when the cycles curve keeps causing the position to recalculate due to the progress not being linear.  I will probably remove the curve I have there now.  I had problems getting the call to get the value to work and while investigating I saw other effects that use the cycles  as an input to get the effect progress position and other effects that grabbed the progress first and used it as an offset to grab the cycles value.  Totally inconsistent.
