### ISSUE TITLE
Incorrect operation of the submodel

### ISSUE THREAD

**Issue by Negr92** [xLightsSequencer/xLights#4094]
Good afternoon. I encountered an incomprehensible error while working with a submodel. 
what I have: 
1) a matrix of 15*20 pixels. 
2) the matrix is divided into 3 submodels (5 lines each) to create a state flag (for example). 
I can assign a color to each submodel (1- yellow, 2- red, 3-blue), I want to assign an appearance effect to the MATRIX model (any of the standard ones), but nothing happens. 
I tried changing the versions of the program, changing the settings, I even reinstalled WINDOWS, but it didn't help.  
yesterday I installed the program version 2023.18 on another computer, made the same settings, and my effects worked successfully. 
but after 24 hours they stopped working again. 

help me solve this problem. there are a lot of settings in the program, maybe I'm doing something wrong.
![3](https://github.com/smeighan/xLights/assets/98332282/19427e98-9051-4eda-be92-a3b4ecb2bf03)
![2](https://github.com/smeighan/xLights/assets/98332282/79d3fd0d-00e8-40fe-b00e-30072481d295)
![1](https://github.com/smeighan/xLights/assets/98332282/51c60d18-9758-4ddf-a45f-d1e52b84e48e)

**Comment by merryoncherry** [comment]
In the scenario pictured, the effects on the submodels are rendering over top of the curtain effect underneath so that you can't see it... that is what is expected and what the first screen shot shows.

Please read this page and make sure you follow what it means:
https://manual.xlights.org/xlights/chapters/chapter-four-sequencer/render-all

Now, you can't actually do anything to the display elements to get the submodels under the main model.  You'd have to make another submodel for the whole matrix, make sure it is in the right place in the submodel list order, and apply your effect to that.

But, this is a lot of work if all you want is horizontal stripes.  Make a second layer on the whole matrix, put a bars effect on there (with 0 cycles, or "Custom Vert"), and you'll be good to go.  This approach will work a lot better if you, say, change your mind and want to use 4 bars, have them move, copy and paste the effect onto another prop, etc.

**Comment by Negr92** [comment]
Thank you very much for your help! you're right! it is necessary to read the manual carefully! the question can be considered closed!

**Comment by derwin12** [comment]
> Thank you very much for your help! you're right! it is necessary to read the manual carefully! the question can be considered closed!

Negr92 - can you close this then? Thanks.

**Comment by Negr92** [comment]
Yes, of course. Thanks

**Comment by derwin12** [comment]
Please Close .. Thanks.
