### ISSUE TITLE
Effect Preset - ignore DMX effects when building the gif preview image

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4178]
Seems like xlights struggles to do this .. and doesnt create anything in the end. So perhaps not bother to create one?

**Comment by AzGilrock** [comment]
So when you say xLights "struggles" what are you seeing?  I just tried this and didn't see anything I'd call struggling.

I did some testing in the debugger and DMXEffects are not rendering at all because they need to get the model from the buffer but since this is a fake model it doesn't exist in the xLights frame objects list of models so the render function automatically returns.  No reason to try to avoid these effects because they are being bypassed anyways and do not generate any data.  I don't believe they are the source of any issues.

<img width="699" alt="Screenshot 2024-02-01 at 7 30 12 PM" src="https://github.com/xLightsSequencer/xLights/assets/2024669/c21b2fb4-094c-4240-af69-d416d1e700d6">
