### ISSUE TITLE
Preset Groups - If you move an empty group, it breaks

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4304]
In the presets window, Add Group. Now grab it and move it (to sort for example). It is no longer a group.
Create the group
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/9d3eda2d-b01b-4ce0-84a3-cb68dcf0b610)
Move the group
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/f6948e41-ffee-476e-b0aa-5e08d05c364a)

Note it lost the > and you cant assign presets to it.
No problem if the group contained presets prior to moving.

**Comment by cybercop23** [comment]
Dare I say... don't move it.... :)

**Comment by Darzoom** [comment]
Funny Alex.....

**Comment by AzGilrock** [comment]
I did a lot of work on that dialog 9 years ago.  Just checked an it wasn't me David Priem added the drag/drop stuff a few years ago.  Whew

Normally I would just say there's no way we can fix this one and let my reverse psychology spur another dev to fix it...lol.

**Comment by cybercop23** [comment]
But you do owe someone a beer now... and I know he drinks and funny things happen.

**Comment by AzGilrock** [comment]
> But you do owe someone a beer now... and I know he drinks and funny things happen.

Show me where anyone solved my positioning issues

**Comment by derwin12** [comment]
Its close .. it does indeed put the > marker to make you think its a group, but you cant add anything to it. If you exit xlights, reload the effects tree - it works again. Is there something about a new group that gets lost - a placeholder effect or something. I have been playing with this for a couple of days.

**Comment by AzGilrock** [comment]
Probably something to do with the underlying node associations.  I forget to test all aspects of it cause I was ready to get off the laptop.  I can look at it again tonight.  Its kinda weird how you have to deal with these trees.  Each item has a wxXmlNode which will have children nodes if its a group.  But the tree is separate so it has its own tree id items which you associate to the XML nodes by setting the item data.  I assumed since you said it was working if the group already had child items that the node data was setup fine so I fixed the marking of the tree id item as having children.
