### ISSUE TITLE
Color Curve Dialog: Hard to click on color selector 

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4368]
Using Windows 10.  In the Color Curve Dialog box, I've found it nearly impossible to click on a color point selector when it is placed on the far right side of the color screen.  

The work-around, which I've been using for a number of seasons, has been to always expand the size of the dialog box to the full width of the screen.  Then, I'm able to hover over and select it.

Can this be updated so you can select the far right color marker?

Thank you for looking.
Clyde L

![image](https://github.com/xLightsSequencer/xLights/assets/12719816/0e5e7fbc-906d-4137-b6b5-e100891e6221)

**Comment by joero4** [comment]
I believe this issue is related to the `GetSize().GetWidth()` returning a width which extends beyond the bounding box that contains the `ColorCurvePanel`.  I can't figure out what's drawing the border around the `ColorCurvePanel` but it appears that total width is being cut off by 3 pixels.  The `ColorCurvePanel` has a total width of 592 when first opened.  by looking at the `Convert` method, and [specifically the calculation of `x`](https://github.com/xLightsSequencer/xLights/blob/31f2a2f1ed229e98bde75a00138363330c9db96c/xLights/ColorCurveDialog.cpp#L77).  I can see that when I move my mouse to the right edge of the `ColorCurvePanel`, `x` will never reach a value greater than 589 before I exit the panel.  This says to me that some portion of the panel (3 pixels) is draw inside this border and not fully visible.  

From my logging I can see the following when I reach the right most portion of the panel...
```
event X: 589 startX: 0.000000 bw: 592.000000 x: 0.994932
```

As you can see my mouse has reached 598, with a total width of 592, which equates to an x of .994932.  When `Normalize` is called, it changes x to be .99 which is what @derwin12 was seeing.  

Simply accounting for these 3 pixels, reduces the width of the visible panel to 589 and allows a value of 1 for x.  This should have a net affect of moving all houses (and timings) drawn to the left by 3 pixels (except for the first one at zero).  

I have made changes locally to account for the 3 pixels when drawing the "houses", and it appears to fix the issue.  This adjustment should follow through for timing marks as well, so I don't see this causing any other potential issues.  I'm working on a pull request for the correction.

**Comment by derwin12** [comment]
Sounds like there is a border around the panel that could perhaps be set to 0?

**Comment by joero4** [comment]
For whatever reason I cannot find what is drawing the border.  I have not done C++ since college so I'm a bit out of my depth here.

**Comment by joero4** [comment]
Ok, I finally found the border.  Setting the border style to `wxBORDER_NONE` fixes most of the issue.  Still seems like it's off by 1 pixel now instead of 3.  Going to tinker a bit more before I submit my PR.

**Comment by joero4** [comment]
Ah, nice.  Thanks @AzGilrock.  I wasn't touching the "//(" and ending with "//)" since I assumed it was generated code.  Didn't realize I could click on the resources tab.  This should be a super easy fix.

**Comment by joero4** [comment]
I'm finding removing the border a little less desirable, especially when your theme is set to light vs dark mode.  Going to request my fix by leaving the board and adjusting for the board width.  Seems solid to me.

**Comment by Clyde-L** [comment]
Thank you guys!  This is so much appreciated!
