### ISSUE TITLE
Should inactive models be flagged in check sequence - for not being on a controller?

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4419]
I am thinking these should not be flagged here..

Models spanning controllers
    ERR: Model '_F48 Remote 1' is not configured for a controller.
    ERR: Model '_F48 Remote 13' is not configured for a controller.
    ERR: Model '_F48 Remote 17' is not configured for a controller.
    ERR: Model '_F48 Remote 25' is not configured for a controller.
    ERR: Model '_F48 Remote 29' is not configured for a controller.
    ERR: Model '_F48 Remote 33' is not configured for a controller.
    ERR: Model '_F48 Remote 41' is not configured for a controller.
    ERR: Model '_F48 Remote 45A' is not configured for a controller.
    ERR: Model '_F48 Remote 45B' is not configured for a controller.
    ERR: Model '_F48 Remote 5' is not configured for a controller.
    ERR: Model '_F48 Remote 9' is not configured for a controller.
    ERR: Model '_PI 1' is not configured for a controller.
    ERR: Model '_PI 2' is not configured for a controller.
    ERR: Model '_PI 3' is not configured for a controller.
    ERR: Model '_PI 4' is not configured for a controller.
    ERR: Model '_PI 5' is not configured for a controller.

**Comment by cybercop23** [comment]
I don't think anyting Inactive (models or ctrls) should have anything done to them, including checking and pinging.

**Comment by keithsw1111** [comment]
I disagree. Downgrading them to warnings may make sense but they should still be called out.

**Comment by keithsw1111** [comment]
Remember check sequence was never about getting no warnings. It was about pointing out potential issues which otherwise might waste user and support resource time identifying.

Even the fact a model is inactive should be a warning in check sequence.


On 21 Mar 2024, at 9:26 am, AlexB ***@***.***> wrote:

﻿

I don't think an Inactive model/controller should have any errors/warnings. The user has specifically inactivated them. I have several images for ctrls, DR, PI and props that i only activate when i need to get a print out of my layout for setup time.
If they really need to be called out, maybe a new section for Inactive Models and the ability in Checkl Sequence to disable them.

**Comment by derwin12** [comment]
In my case they are just place holders in my layout - for others it could be off season props or props not yet purchased or deployed.
Just realized maybe I am making use of a feature/bug.  The active is under "appearance" - if you make a model inactive it hides it from the layout *but* if you mark an image model inactive it does **not** remove it from the layout. I seem to be taking advantage of that little trick.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/5d892114-beea-48aa-9e26-eb003efec372)

**Comment by derwin12** [comment]
I see that now .. having dug into your response. Are you okay with making a warning as Keith pointed out, as it should/could be on a controller even if it is inactive.  It should not be ignored, but its not really a show stopping error either.

**Comment by dkulp** [comment]
Yea... I use the "Inactive" feature to mark props that I no longer am using, but I want to keep the prop and channel assignments and such so that when I load older sequences, I don't have the "This prop cannot be found" error popup.    For example, years ago for halloween, my son and I had light up stick man suits that I added to the halloween sequences.   We haven't used them since covid, but I want to keep them in the sequences so if we do decide to do them again, they are there, but not visible for now.

**Comment by cybercop23** [comment]
So users found "creative" ways to use this "feature". It shouldn't be changed this late, and if we _need_ to flag it, it shoudl be in its own section, Inactive Models; users have specifically inactivated them and we can just remind them of that fact.
