### ISSUE TITLE
xLights 2024.16 stuck in loop and keeps asking to "reselect media folder" - will not allow any folder to be chosen

### ISSUE THREAD

**Issue by tbetgeorge** [xLightsSequencer/xLights#4833]
![Screenshot 2024-09-25 at 8 15 45 AM](https://github.com/user-attachments/assets/8d8eb216-faeb-4f13-aae2-1bfc010f065e)

**Describe the bug**
Can't get past first screen to even open program. Keeps asking to "reselect media folder"

**To Reproduce**
1. Open xLights

**Versions (please complete the following information):**
 - OS: Mac Sequoia 15.0
 - xLights version [e.g. 2024.16]
 - iMac Pro 2017

**Comment by kylegrymonprez** [comment]
We've seen some issues with some Media directories being added into Preferences>Sequences>Media/Resource Directories that just.....don't work. Since you can't seem to launch the UI, you can try manually updating the settings to see if it helps.

Navigate to "~/Library/Containers/org.xlights/Data/Library/Preferences" and open "xLights Preferences" in a text editor. Copy/backup the entry for "MediaDir" and reset it to "MediaDir="

Relaunch and see if that helps. You should then be able to re-add the directories as needed, but there may be old entries in there that are no longer relevant causing issues.

**Comment by cybercop23** [comment]
@tbetgeorge yes, no, maybeso?

**Comment by thekev** [comment]
#4786

**Comment by tjenvy** [comment]
This doesnt work as the directory is empty just as Kyle says to change it to.
