### ISSUE TITLE
Check updates failed - page is hitting a redirect. No newer versions found

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4898]
In windows checking for updates it doesnt find anything when doing the check.
Running thru debug it is only seeing this 

Moved Permanently
The document has moved [here](https://xlights.org/releases/).

So it is not getting the downloads page to parse for new versions.

![image](https://github.com/user-attachments/assets/55392e5b-4bfd-4aeb-9852-8d7127c5b926)

**Comment by cybercop23** [comment]
The downloads page used to be a www/dirlist of the folder containing the files. Looks like that setting may have been removed recently... .13ish.

![image](https://github.com/user-attachments/assets/a7783fc0-9642-456e-9161-ac325859cc55)

Related... can we finalize the xSchedule issue so it can be built in Git and move the downloads to Git? Or...  since there hasn't been any changes to xSchedule in a while can that be made its own download?

**Comment by derwin12** [comment]
Scott has fixed this.

**Comment by keithsw1111** [comment]
Xschedule changes every release due to changes in common files.

Sent from my iPhone

On 15 Oct 2024, at 5:18 AM, AlexB ***@***.***> wrote:

﻿

The downloads page used to be a www/dirlist of the folder containing the files. Looks like that setting may have been removed recently... .13ish.

image.png (view on web)<https://github.com/user-attachments/assets/a7783fc0-9642-456e-9161-ac325859cc55>

Related... can we finalize the xSchedule issue so it can be built in Git and move the downloads to Git? Or... since there hasn't been any changes to xSchedule in a while can that be made its own download?
