### ISSUE TITLE
Time Sync

### ISSUE THREAD

**Issue by RobinAA2** [xLightsSequencer/xLights#4919]
**Is your feature request related to a problem? Please describe.**
When using custom controllers, they may have a time delay, causing the audio to be ahead of the lights. Similarly, audio delays, such as from Bluetooth speakers, cause lights to be ahead of the audio.

**Describe the solution you'd like**
Would like an adjustment panel for both audio and each controller, to add delays as needed to allow time synchronization. Numeric entry boxes next to audio and each controller for refined millisecond control is sufficient. Optionally add sliders to adjust as well.

**Describe alternatives you've considered**
I can adjust my controller to be slower in the case of delayed audio, such as bluetooth, but don't have the ability to adjust faster than xlights provides signals.

**Additional context**
I am using an arduino solution which takes in generic serial, then broadcasts udp to several other arduino endpoints. The wifi devices I am using are ESP-01S, and they have delays which I can do nothing about. The music is ahead of the lights, in this case.

**Comment by cybercop23** [comment]
Even with a delay built in or a slider of sorts, there are lots of other external environmental items that can affect the output from one day to the next, even one song to the next. I don't think this is something that xlights needs to handle. 
That's why ctrl that need to be send data, are wired and those that are wireless run multisync. Can you add an SD card to ec of those devices and store their relative channel data for each sequence and use multisync? So instead of sending the actual channel data, send a timemark to tell them where to play and keep frames in sync.

**Comment by RobinAA2** [comment]
Thanks for the quick response. I am not familiar with multisync, but I dont understand how it can help my situation. Even if I was to send just a timestamp, instead of my current 6 bytes (rgb only with a crc) per xlights 80hz or so generic serial message, the problem is the delay to the timestamp still exists and it would be just as far behind. Note I am only sending 6 bytes every time xlights sends me data, it is simply 500ms or so latency transmitting, not a throughput issue. Note, the same setup doesn't have the same latency problem when I use HC-05 modules, but I can't use that because they are point to point instead of multicast to 20+ devices.

**Comment by derwin12** [comment]
Sounds more like an FPP request -note FPP has an overall delay settings but it is not per output. Suggest taking the discussion over there.
